version: "3.4"

services:
  serviceb:
    image: ${DOCKER_REGISTRY-}serviceb
    build:
      context: .
      dockerfile: ServiceB/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/ServiceB.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=crypticpassword
    ports:
      - "6101:80"
      - "6100:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${USERPROFILE}\.aspnet\Https:/https/:ro
