version: "3.8"

services:
  servicea:
    image: ${DOCKER_REGISTRY-}servicea
    build:
      context: .
      dockerfile: ServiceA/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/ServiceA.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=test
    ports:
      - "4100:443"
