version: "3.8"

services:
  serviceb:
    image: ${DOCKER_REGISTRY-}serviceb
    build:
      context: .
      dockerfile: ServiceB/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/ServiceB.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=test
    ports:
      - "5100:443"
