version_info: "0"
resources:
  - "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
    name: servicea
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: servicea
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: servicea
                    port_value: 443

    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext

  - "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
    name: serviceb
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: serviceb
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: serviceb
                    port_value: 443

    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
